### ISSUE TITLE
zimscrapperlib.zim.items not found, no module named as such

### ISSUE THREAD

**Issue by gajanangitte** [openzim/kolibri2zim#32]
Recently, I installed kolibri2zim.
Process followed:
1. created a virtualenv
2. git cloned the repo
3. pip3 install -r requirements.txt
4. python3 setup.py install
5. kolibri2zim --name="School Of Thought" --channel-id="305b12ea5ea84fa18f933705c23f5ee0" --description="All about fallacies" --low-quality --title="School Of Thhhought"

Error:

Traceback (most recent call last):
  File "/home/apricot/Desktop/kiwix-org/bin/kolibri2zim", line 11, in <module>
    load_entry_point('kolibri2zim==1.0.0.dev0', 'console_scripts', 'kolibri2zim')()
  File "/home/apricot/Desktop/kiwix-org/lib/python3.8/site-packages/kolibri2zim-1.0.0.dev0-py3.8.egg/kolibri2zim/__main__.py", line 15, in main
    entry()
  File "/home/apricot/Desktop/kiwix-org/lib/python3.8/site-packages/kolibri2zim-1.0.0.dev0-py3.8.egg/kolibri2zim/entrypoint.py", line 181, in main
    from .scraper import Kolibri2Zim
  File "/home/apricot/Desktop/kiwix-org/lib/python3.8/site-packages/kolibri2zim-1.0.0.dev0-py3.8.egg/kolibri2zim/scraper.py", line 22, in <module>
    from zimscraperlib.zim.items import URLItem, StaticItem
ModuleNotFoundError: No module named 'zimscraperlib.zim.items'

**Comment by rgaudin** [comment]
@gajanangitte, sorry about that. kolibri2zim requires an unreleased version of zimscraperlib. Will probably be named `1.4` but the requirements allows install of 1.3.
That zimscraperlib has not been released yet because it itself depends on pylibzim release which we're waiting for.
Check the Dockerfile for linux version of both wheels or build it yourself off both master's.

If you're just planning on using it, the best of to use the docker image.
